language: ruby
rvm:
- 2.2.0
cache: bundler
bundler_args: "--without production --deployment"
before_install:
- gem install bundler --pre
- npm install
- $(npm bin)/gulp dtsm
- $(npm bin)/gulp dtsm:test
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- bundle exec rspec
- $(npm bin)/gulp test
notifications:
  slack:
    secure: V1K9VdHy0F3Hm3aaBoSzNxcMd31pfhaB6b2mbiaqyDygpoHcd1mYHYlrlSL41Zn2OJslPwrZYAIXlR9dk8p8dnYThsfqmKGzjCiG1Be6v0R9H5lmDnPjCLFDFTFlcMSBPPDv9XJjkdySH8EdMvyQhQsfFwt01HMlwONq/bDCc+A=
