---
"$schema": http://json-schema.org/draft-04/hyper-schema
description: A schema for ANCT reschedulings API
id: http://www.akashi.ac.jp/actopus/schema#
links:
- href: http://actopus.akashi.ac.jp/
  rel: self
title: actopus API
