department:
  - name: 機械工学科
    abbreviation_name: M
  - name: 電気情報工学科
    abbreviation_name: E
  - name: 都市システム工学科
    abbreviation_name: C
  - name: 建築学科
    abbreviation_name: A
  - name: 専攻科
    abbreviation_name: Adv

course:
  - name: 電気電子工学コース
    abbreviation_name: D
  - name: 情報工学コース
    abbreviation_name: J
  - name: 機械・電子システム工学専攻
    abbreviation_name: ME
  - name: 建築・都市システム工学専攻
    abbreviation_name: AD

period:
  - name: 1
    begin_at: '09:00:00+09:00'
    end_at: '10:30:00+09:00'
  - name: 2
    begin_at: '10:40:00+09:00'
    end_at: '12:10:00+09:00'
  - name: 3
    begin_at: '13:00:00+09:00'
    end_at: '14:30:00+09:00'
  - name: 4
    begin_at: '14:40:00+09:00'
    end_at: '16:10:00+09:00'
  - name: 5
    begin_at: '16:20:00+09:00'
    end_at: '17:50:00+09:00'
  - name: 1F
    begin_at: '09:00:00+09:00'
    end_at: '09:45:00+09:00'
  - name: 1S
    begin_at: '09:45:00+09:00'
    end_at: '10:30:00+09:00'
  - name: 2F
    begin_at: '10:40:00+09:00'
    end_at: '11:25:00+09:00'
  - name: 2S
    begin_at: '11:25:00+09:00'
    end_at: '12:10:00+09:00'
  - name: 3F
    begin_at: '13:00:00+09:00'
    end_at: '13:45:00+09:00'
  - name: 3S
    begin_at: '13:45:00+09:00'
    end_at: '14:30:00+09:00'
