timetable:
  beginning_of_day: '09:00:00+09:00'
  end_of_day: '18:20:00+09:00'

department:
  - name: 一般科目
    abbreviation_name: G
  - name: 機械工学科
    abbreviation_name: M
  - name: 電気情報工学科
    abbreviation_name: E
  - name: 都市システム工学科
    abbreviation_name: C
  - name: 建築学科
    abbreviation_name: A
  - name: 専攻科
    abbreviation_name: Adv

course:
  - name: 電気電子工学コース
    abbreviation_name: D
  - name: 情報工学コース
    abbreviation_name: J
  - name: 機械・電子システム工学専攻
    abbreviation_name: ME
  - name: 建築・都市システム工学専攻
    abbreviation_name: AD

period:
  - name: '1'
    start_time: '09:00:00+09:00'
    end_time: '10:30:00+09:00'
  - name: '2'
    start_time: '10:40:00+09:00'
    end_time: '12:10:00+09:00'
  - name: '3'
    start_time: '13:00:00+09:00'
    end_time: '14:30:00+09:00'
  - name: '4'
    start_time: '14:40:00+09:00'
    end_time: '16:10:00+09:00'
  - name: '5'
    start_time: '16:20:00+09:00'
    end_time: '17:50:00+09:00'
  - name: 1F
    start_time: '09:00:00+09:00'
    end_time: '09:45:00+09:00'
  - name: 1S
    start_time: '09:45:00+09:00'
    end_time: '10:30:00+09:00'
  - name: 2F
    start_time: '10:40:00+09:00'
    end_time: '11:25:00+09:00'
  - name: 2S
    start_time: '11:25:00+09:00'
    end_time: '12:10:00+09:00'
  - name: 3F
    start_time: '13:00:00+09:00'
    end_time: '13:45:00+09:00'
  - name: 3S
    start_time: '13:45:00+09:00'
    end_time: '14:30:00+09:00'
  - name: 4F
    start_time: '14:40:00+09:00'
    end_time: '15:25:00+09:00'
  - name: 4S
    start_time: '15:25:00+09:00'
    end_time: '16:10:00+09:00'
