github_repo: 'https://github.com/izumin5210/actopus'

version: 1.0

timetable:
  beginning_of_day: '09:00:00+09:00'
  end_of_day: '18:20:00+09:00'
  weekdays:
  - 1
  - 2
  - 3
  - 4
  - 5

klass:
  category:
    undergraduate: 0
    advanced: 10

lecture:
  special_target:
    female: 20
    overseas_student: 40
