department:
  - name: 機械工学科
    abbreviation_name: M
  - name: 電気情報工学科
    abbreviation_name: E
  - name: 都市システム工学科
    abbreviation_name: C
  - name: 建築学科
    abbreviation_name: A
  - name: 専攻科
    abbreviation_name: Adv

course:
  - name: 電気電子工学コース
    abbreviation_name: D
  - name: 情報工学コース
    abbreviation_name: J
  - name: 機械・電子システム工学専攻
    abbreviation_name: ME
  - name: 建築・都市システム工学専攻
    abbreviation_name: AD
